name: Build and Publish Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install amago
        run: |
          pip install --upgrade pip
          pip install -e .

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            sphinx \
            sphinx-rtd-theme \
            gin-config \
            sphinx-autodoc-typehints \
            sphinx-book-theme

      - name: Build Sphinx HTML
        run: |
          cd docs
          make clean html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build/html
